In [2]:
import numpy as np
from scipy.sparse import csr_matrix, linalg

# Create a sparse matrix
data = np.array([1, 2, 3, 4, 5, 6])
row_indices = np.array([0, 0, 1, 1, 2, 2])
col_indices = np.array([0, 2, 1, 2, 0, 1])
A = csr_matrix((data, (row_indices, col_indices)), shape=(3, 3))

# Compute LU decomposition
LU = linalg.splu(A)

# Solve for the inverse
A_inv = LU.solve(np.eye(3))

print(A_inv)

print("Inverse of A:")
print(A_inv.toarray())


[[ 0.44444444 -0.22222222  0.11111111]
 [-0.37037037  0.18518519  0.07407407]
 [ 0.27777778  0.11111111 -0.05555556]]
Inverse of A:


C:\Users\Rishabh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


AttributeError: 'numpy.ndarray' object has no attribute 'toarray'